name: Check source against policy

on: [push]

jobs:
  conftest:
    name: Run conftest
    runs-on: 'ubuntu-latest'
    
    steps:
      - uses: actions/checkout@v1

      - name: Install conftest
        run: |
          apt update
          apt install wget
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.21.0/conftest_0.21.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.21.0_Linux_x86_64.tar.gz
      - name: Check against policy
        run: |
          ls
          pushd app/test
          ../../conftest test ../src/*
          popd
