name: labels

on:
  pull_request:
    types:
      - opened

jobs:
  label_pr:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on branch prefix
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: /pr-labels.yaml
        env:
          GITHUB_TOKEN: ${{ github.token }}
